### ISSUE TITLE
http://blog.howie6879.cn/atom.xml失效了

### ISSUE THREAD

**Issue by starrye** [howie6879/Sanic-For-Pythoneer#5]
老哥，http://blog.howie6879.cn/atom.xml失效了～

**Comment by howie6879** [comment]
换成 https://www.howie6879.cn/atom.xml
或者 https://www.howie6879.cn/index.xml

lwz <notifications@github.com> 于2021年2月25日周四 下午2:09写道：

**Comment by starrye** [comment]
可以了 感谢老哥
